# Generated by Django 3.2 on 2021-05-05 12:56

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('course_fee', models.IntegerField(blank=True, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=250, null=True)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='front/images')),
                ('course_video', models.FileField(blank=True, default='', null=True, upload_to='instructor/module/session', verbose_name='')),
                ('course_requirement', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('course_level', models.CharField(blank=True, max_length=150, null=True)),
                ('course_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('course_slug', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('course_why_take', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_appiled', models.NullBooleanField(default=False)),
                ('is_verified', models.NullBooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Modules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(blank=True, max_length=500, null=True)),
                ('module_desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.course')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Course_Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=2150, null=True)),
                ('session_desc', models.TextField(blank=True, null=True)),
                ('is_appiled', models.NullBooleanField(default=False)),
                ('is_verified', models.NullBooleanField(default=False)),
                ('session_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('course_in_pdf', models.FileField(blank=True, null=True, upload_to='Course_Session/Docs')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('video_link', models.FileField(blank=True, default='', max_length=2000, null=True, upload_to='instructor/module/session', verbose_name='')),
                ('course_slug', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('position', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.course_modules')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='viewed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('module_position', models.CharField(blank=True, max_length=50, null=True)),
                ('session_position', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
        migrations.CreateModel(
            name='SessionComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.sessioncomments')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.course_session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(max_length=250, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.coursecategory')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.coursesubcategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs'),
        ),
    ]
