# Generated by Django 3.0.5 on 2020-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_modules',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course_session',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
