# Generated by Django 3.0.5 on 2020-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20200517_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_appiled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='course_session',
            name='is_appiled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='course_session',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
