# Generated by Django 3.0.5 on 2020-05-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200517_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_session',
            name='video_link',
            field=models.FileField(blank=True, default='', max_length=2000, null=True, upload_to='instructor/module/session', verbose_name=''),
        ),
    ]
