# Generated by Django 3.0.5 on 2020-05-17 12:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
