# Generated by Django 3.0.5 on 2020-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200517_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
