# Generated by Django 3.0.5 on 2020-05-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_students_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='is_appiled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='is_appiled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
